# Author: Aisha Shah
# Date: 2025-02-25
# Version: 0.1
# Description: Configuration file for SuspectPeak_Hunter pipeline 
#             This file contains all the parameters that can be modified by the user
#             to run the pipeline.
#             The pipeline is designed to run on a SLURM cluster.




#*******************************#
# General settings              #
#*******************************#

# Working directory
workdir: "/work/FAC/FBM/CIG/nvastenh/competition_model/Aisha-Dora/snakemake/SuspectPeak_Hunter"

# Results directory
results_dir: "results"

# Genome information
genome: "Danio_rerio.GRCz11.dna_sm.primary_assembly"

# Sample information
all_samples: "array_rep1.wo_IgG.wo_NegCtrls.tsv" 
## The following files should be a tab-separated file with the following columns:
## SampleID, Group, Active, Inactive, TF, IgG, NegCtrls, Replicate, Read1, Read2
## Group: Active, Inactive, TF
## Active: Active mark ChIP-seq sample
## Inactive: Inactive mark ChIP-seq sample
## TF: TF ChIP-seq sample
## IgG: IgG control sample
## NegCtrls: Negative control sample
## Replicate: Replicate number
## Read1: Path to read1 fastq file
## Read2: Path to read2 fastq file
## These files can be generated using the script "scripts/generate_bootstrap_arrays.py"
## If not generated by our script please save them in the same format as described above and then provide the path to the file below
SL_generation_samples: "SL_generation_samples.tsv"
validation_samples: "validation_samples.array"

#*******************************#
# File settings                 #
#*******************************#
# If True, the pipeline will keep the intermediate files
# If False, the pipeline will delete the intermediate files
keep_trimmed_reads_fastq: "True"
keep_Raw_BAMs: "False"
keep_BAMs_wo_MT: "True"
keep_filtered_BAMs: "True"
keep_genomecov_bedgraph: "True"
keep_Peaks: "True"

#*******************************#
# Trimming and mapping settings #
#*******************************#

# Parameters for Trimgalore
# --quality: Phred score for quality trimming
# --length: Minimum length of reads to keep after trimming
# --stringency: Overlap with adapter sequence required to trim a read
# -e: Error rate
# --illumina: Use Illumina adapter sequence
# Additional parameters can be found at:

trim_galore_pe:
  additional_params: "--quality 20 --length 20 --stringency 1 -e 0.1"
  threads: 24
  skip_trimming: "False"  
trim_galore_se:
  additional_params: "--illumina -q 20 --length 20 --stringency 5 -e 0.5"
  threads: 24
  skip_trimming: "False" 

# Mapping parameters for bowtie2
# ** --no-unal is very important else downstream files will ahve unaligned reads that will not be understood by genome cov and you will get an error
# --no-mixed: Discard reads that are not properly paired
# --no-unal: Discard unaligned reads
# --very-sensitive-local: Very sensitive local alignment
# additional parameters can be found at: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
map_bowtie2_se:
  additional_params: "--very-sensitive-local --no-unal"
  threads: 24
map_bowtie2_pe:
  additional_params: "--very-sensitive-local --no-mixed --no-unal --dovetail -X 1000"
  threads: 24

#*******************************#
# BootStrapping                 #
#*******************************#
bootstrap_samples:
  rounds: 10           # Number of bootstrap iterations
  samples_per_group: 3 # Number of samples per bootstrap iteration from each group (groups are Active, Inactive mark, TF)
  seed: 1              # Seed for random number generator to select samples

#*******************************#
# Downsampling                  #
#*******************************#

DownSample:
  Reads: "10000000" #"3000000" 
  Reads_PE: "20000000" #"6000000"
  Reads_SE: "10000000" #"3000000"
  threads: 8
GenMap:
  MinMap: "0.3"

#*******************************#
# Peak calling settings         #
#*******************************#
# Peak calling using SEACR
peak_calling:
  mode: "stringent"
  threshold: "0.1"  # "0.1" "0.2" # "0.5" "0.9" "1" "0.001"
  normalization: "non"
  filter_by_depth: True
  min_depth: 5

#*******************************# 
# Suspect list generation       #
#*******************************#
# Parameters for suspect list generation
# num_of_samples: Number of samples in the bootstrap round
# minimum_length: Minimum length of the region to be suspectlisted
# percentage_threshold: Percentage of bootstrap rounds that should have a region to be suspectlisted
# min_num_of_bootstrap_rounds: Minimum number of bootstrap rounds that should have a region to be suspectlisted

generate_suspectList:
  # per bootstrap round
  num_of_samples: "9"
  minimum_length: "10"
  percentage_threshold: "80"
  # min number of bootstrap rounds that should have a region to be suspectlisted
  min_num_of_bootstrap_rounds: 5
