# Genome information
genome: "Danio_rerio.GRCz11.dna_sm.primary_assembly"

# Sample information
SL_array: "array.tsv"
ApplySL_array: "PRJNA738523.samples.array"

# File retention settings
keep_trimmed_reads_fastq: "True"
keep_BAMs: "True"
keep_filtered_BAMs: "True"
keep_genomecov_bedgraph: "True"
keep_Peaks: "True"

# Trimming and mapping settings
skip_trimming: "False"  # Set to "True" to skip trimming
skip_mapping: "False"   # Set to "True" to skip mapping

# Input file type provided:
# BAMs_provided: "False"
# Trimmed_fastq_provided: "False"
# Fastq_provided: "True"

# Parameters for Trimgalore
trim_galore_pe:
  additional_params: "-q 20 --length 20 --stringency 5"
trim_galore_se:
  additional_params: "--illumina -q 20 --length 20 --stringency 5"

# Mapping parameters for bowtie2
map_bowtie2_se:
  additional_params: "--very-sensitive-local --no-unal"
map_bowtie2_pe:
  additional_params: "--very-sensitive-local --no-mixed --no-unal --dovetail -X 1000"

# Peak calling settings
peak_calling:
  mode: "stringent"
  threshold: "0.001"
  normalization: "non"

# Suspect list generation settings
generate_suspectList:
  num_of_samples: "3"
  minimum_length: "10"
  percentage_threshold: "60"
